name: Build image
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-22.04
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    # Configure
    - name: Configure
      run: bash ./br_config.sh

    # Build
    - name: Build
      run: |
        cd build && make

    # Upload image
    - name: 'Upload image'
      uses: actions/upload-artifact@v4
      with:
        name: sdcard-${{ github.ref }}.img
        path: build/images/sdcard.img
